// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.com/21keshav/UserManagementSystem/util"
	"go.mongodb.org/mongo-driver/mongo"
)

type FakeMongoClient struct {
	FindObjectStub        func(string, string, interface{}, interface{}) error
	findObjectMutex       sync.RWMutex
	findObjectArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 interface{}
		arg4 interface{}
	}
	findObjectReturns struct {
		result1 error
	}
	findObjectReturnsOnCall map[int]struct {
		result1 error
	}
	FindUserStub        func(string, string, util.User) (util.User, error)
	findUserMutex       sync.RWMutex
	findUserArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 util.User
	}
	findUserReturns struct {
		result1 util.User
		result2 error
	}
	findUserReturnsOnCall map[int]struct {
		result1 util.User
		result2 error
	}
	GetCollectionStub        func(string, string) *mongo.Collection
	getCollectionMutex       sync.RWMutex
	getCollectionArgsForCall []struct {
		arg1 string
		arg2 string
	}
	getCollectionReturns struct {
		result1 *mongo.Collection
	}
	getCollectionReturnsOnCall map[int]struct {
		result1 *mongo.Collection
	}
	GetDatabaseStub        func(string) *mongo.Database
	getDatabaseMutex       sync.RWMutex
	getDatabaseArgsForCall []struct {
		arg1 string
	}
	getDatabaseReturns struct {
		result1 *mongo.Database
	}
	getDatabaseReturnsOnCall map[int]struct {
		result1 *mongo.Database
	}
	InsertDataStub        func(string, string, interface{}) (*mongo.InsertOneResult, error)
	insertDataMutex       sync.RWMutex
	insertDataArgsForCall []struct {
		arg1 string
		arg2 string
		arg3 interface{}
	}
	insertDataReturns struct {
		result1 *mongo.InsertOneResult
		result2 error
	}
	insertDataReturnsOnCall map[int]struct {
		result1 *mongo.InsertOneResult
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeMongoClient) FindObject(arg1 string, arg2 string, arg3 interface{}, arg4 interface{}) error {
	fake.findObjectMutex.Lock()
	ret, specificReturn := fake.findObjectReturnsOnCall[len(fake.findObjectArgsForCall)]
	fake.findObjectArgsForCall = append(fake.findObjectArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 interface{}
		arg4 interface{}
	}{arg1, arg2, arg3, arg4})
	fake.recordInvocation("FindObject", []interface{}{arg1, arg2, arg3, arg4})
	fake.findObjectMutex.Unlock()
	if fake.FindObjectStub != nil {
		return fake.FindObjectStub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.findObjectReturns
	return fakeReturns.result1
}

func (fake *FakeMongoClient) FindObjectCallCount() int {
	fake.findObjectMutex.RLock()
	defer fake.findObjectMutex.RUnlock()
	return len(fake.findObjectArgsForCall)
}

func (fake *FakeMongoClient) FindObjectCalls(stub func(string, string, interface{}, interface{}) error) {
	fake.findObjectMutex.Lock()
	defer fake.findObjectMutex.Unlock()
	fake.FindObjectStub = stub
}

func (fake *FakeMongoClient) FindObjectArgsForCall(i int) (string, string, interface{}, interface{}) {
	fake.findObjectMutex.RLock()
	defer fake.findObjectMutex.RUnlock()
	argsForCall := fake.findObjectArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeMongoClient) FindObjectReturns(result1 error) {
	fake.findObjectMutex.Lock()
	defer fake.findObjectMutex.Unlock()
	fake.FindObjectStub = nil
	fake.findObjectReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeMongoClient) FindObjectReturnsOnCall(i int, result1 error) {
	fake.findObjectMutex.Lock()
	defer fake.findObjectMutex.Unlock()
	fake.FindObjectStub = nil
	if fake.findObjectReturnsOnCall == nil {
		fake.findObjectReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.findObjectReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeMongoClient) FindUser(arg1 string, arg2 string, arg3 util.User) (util.User, error) {
	fake.findUserMutex.Lock()
	ret, specificReturn := fake.findUserReturnsOnCall[len(fake.findUserArgsForCall)]
	fake.findUserArgsForCall = append(fake.findUserArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 util.User
	}{arg1, arg2, arg3})
	fake.recordInvocation("FindUser", []interface{}{arg1, arg2, arg3})
	fake.findUserMutex.Unlock()
	if fake.FindUserStub != nil {
		return fake.FindUserStub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.findUserReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeMongoClient) FindUserCallCount() int {
	fake.findUserMutex.RLock()
	defer fake.findUserMutex.RUnlock()
	return len(fake.findUserArgsForCall)
}

func (fake *FakeMongoClient) FindUserCalls(stub func(string, string, util.User) (util.User, error)) {
	fake.findUserMutex.Lock()
	defer fake.findUserMutex.Unlock()
	fake.FindUserStub = stub
}

func (fake *FakeMongoClient) FindUserArgsForCall(i int) (string, string, util.User) {
	fake.findUserMutex.RLock()
	defer fake.findUserMutex.RUnlock()
	argsForCall := fake.findUserArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeMongoClient) FindUserReturns(result1 util.User, result2 error) {
	fake.findUserMutex.Lock()
	defer fake.findUserMutex.Unlock()
	fake.FindUserStub = nil
	fake.findUserReturns = struct {
		result1 util.User
		result2 error
	}{result1, result2}
}

func (fake *FakeMongoClient) FindUserReturnsOnCall(i int, result1 util.User, result2 error) {
	fake.findUserMutex.Lock()
	defer fake.findUserMutex.Unlock()
	fake.FindUserStub = nil
	if fake.findUserReturnsOnCall == nil {
		fake.findUserReturnsOnCall = make(map[int]struct {
			result1 util.User
			result2 error
		})
	}
	fake.findUserReturnsOnCall[i] = struct {
		result1 util.User
		result2 error
	}{result1, result2}
}

func (fake *FakeMongoClient) GetCollection(arg1 string, arg2 string) *mongo.Collection {
	fake.getCollectionMutex.Lock()
	ret, specificReturn := fake.getCollectionReturnsOnCall[len(fake.getCollectionArgsForCall)]
	fake.getCollectionArgsForCall = append(fake.getCollectionArgsForCall, struct {
		arg1 string
		arg2 string
	}{arg1, arg2})
	fake.recordInvocation("GetCollection", []interface{}{arg1, arg2})
	fake.getCollectionMutex.Unlock()
	if fake.GetCollectionStub != nil {
		return fake.GetCollectionStub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.getCollectionReturns
	return fakeReturns.result1
}

func (fake *FakeMongoClient) GetCollectionCallCount() int {
	fake.getCollectionMutex.RLock()
	defer fake.getCollectionMutex.RUnlock()
	return len(fake.getCollectionArgsForCall)
}

func (fake *FakeMongoClient) GetCollectionCalls(stub func(string, string) *mongo.Collection) {
	fake.getCollectionMutex.Lock()
	defer fake.getCollectionMutex.Unlock()
	fake.GetCollectionStub = stub
}

func (fake *FakeMongoClient) GetCollectionArgsForCall(i int) (string, string) {
	fake.getCollectionMutex.RLock()
	defer fake.getCollectionMutex.RUnlock()
	argsForCall := fake.getCollectionArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeMongoClient) GetCollectionReturns(result1 *mongo.Collection) {
	fake.getCollectionMutex.Lock()
	defer fake.getCollectionMutex.Unlock()
	fake.GetCollectionStub = nil
	fake.getCollectionReturns = struct {
		result1 *mongo.Collection
	}{result1}
}

func (fake *FakeMongoClient) GetCollectionReturnsOnCall(i int, result1 *mongo.Collection) {
	fake.getCollectionMutex.Lock()
	defer fake.getCollectionMutex.Unlock()
	fake.GetCollectionStub = nil
	if fake.getCollectionReturnsOnCall == nil {
		fake.getCollectionReturnsOnCall = make(map[int]struct {
			result1 *mongo.Collection
		})
	}
	fake.getCollectionReturnsOnCall[i] = struct {
		result1 *mongo.Collection
	}{result1}
}

func (fake *FakeMongoClient) GetDatabase(arg1 string) *mongo.Database {
	fake.getDatabaseMutex.Lock()
	ret, specificReturn := fake.getDatabaseReturnsOnCall[len(fake.getDatabaseArgsForCall)]
	fake.getDatabaseArgsForCall = append(fake.getDatabaseArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("GetDatabase", []interface{}{arg1})
	fake.getDatabaseMutex.Unlock()
	if fake.GetDatabaseStub != nil {
		return fake.GetDatabaseStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.getDatabaseReturns
	return fakeReturns.result1
}

func (fake *FakeMongoClient) GetDatabaseCallCount() int {
	fake.getDatabaseMutex.RLock()
	defer fake.getDatabaseMutex.RUnlock()
	return len(fake.getDatabaseArgsForCall)
}

func (fake *FakeMongoClient) GetDatabaseCalls(stub func(string) *mongo.Database) {
	fake.getDatabaseMutex.Lock()
	defer fake.getDatabaseMutex.Unlock()
	fake.GetDatabaseStub = stub
}

func (fake *FakeMongoClient) GetDatabaseArgsForCall(i int) string {
	fake.getDatabaseMutex.RLock()
	defer fake.getDatabaseMutex.RUnlock()
	argsForCall := fake.getDatabaseArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeMongoClient) GetDatabaseReturns(result1 *mongo.Database) {
	fake.getDatabaseMutex.Lock()
	defer fake.getDatabaseMutex.Unlock()
	fake.GetDatabaseStub = nil
	fake.getDatabaseReturns = struct {
		result1 *mongo.Database
	}{result1}
}

func (fake *FakeMongoClient) GetDatabaseReturnsOnCall(i int, result1 *mongo.Database) {
	fake.getDatabaseMutex.Lock()
	defer fake.getDatabaseMutex.Unlock()
	fake.GetDatabaseStub = nil
	if fake.getDatabaseReturnsOnCall == nil {
		fake.getDatabaseReturnsOnCall = make(map[int]struct {
			result1 *mongo.Database
		})
	}
	fake.getDatabaseReturnsOnCall[i] = struct {
		result1 *mongo.Database
	}{result1}
}

func (fake *FakeMongoClient) InsertData(arg1 string, arg2 string, arg3 interface{}) (*mongo.InsertOneResult, error) {
	fake.insertDataMutex.Lock()
	ret, specificReturn := fake.insertDataReturnsOnCall[len(fake.insertDataArgsForCall)]
	fake.insertDataArgsForCall = append(fake.insertDataArgsForCall, struct {
		arg1 string
		arg2 string
		arg3 interface{}
	}{arg1, arg2, arg3})
	fake.recordInvocation("InsertData", []interface{}{arg1, arg2, arg3})
	fake.insertDataMutex.Unlock()
	if fake.InsertDataStub != nil {
		return fake.InsertDataStub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.insertDataReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeMongoClient) InsertDataCallCount() int {
	fake.insertDataMutex.RLock()
	defer fake.insertDataMutex.RUnlock()
	return len(fake.insertDataArgsForCall)
}

func (fake *FakeMongoClient) InsertDataCalls(stub func(string, string, interface{}) (*mongo.InsertOneResult, error)) {
	fake.insertDataMutex.Lock()
	defer fake.insertDataMutex.Unlock()
	fake.InsertDataStub = stub
}

func (fake *FakeMongoClient) InsertDataArgsForCall(i int) (string, string, interface{}) {
	fake.insertDataMutex.RLock()
	defer fake.insertDataMutex.RUnlock()
	argsForCall := fake.insertDataArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeMongoClient) InsertDataReturns(result1 *mongo.InsertOneResult, result2 error) {
	fake.insertDataMutex.Lock()
	defer fake.insertDataMutex.Unlock()
	fake.InsertDataStub = nil
	fake.insertDataReturns = struct {
		result1 *mongo.InsertOneResult
		result2 error
	}{result1, result2}
}

func (fake *FakeMongoClient) InsertDataReturnsOnCall(i int, result1 *mongo.InsertOneResult, result2 error) {
	fake.insertDataMutex.Lock()
	defer fake.insertDataMutex.Unlock()
	fake.InsertDataStub = nil
	if fake.insertDataReturnsOnCall == nil {
		fake.insertDataReturnsOnCall = make(map[int]struct {
			result1 *mongo.InsertOneResult
			result2 error
		})
	}
	fake.insertDataReturnsOnCall[i] = struct {
		result1 *mongo.InsertOneResult
		result2 error
	}{result1, result2}
}

func (fake *FakeMongoClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.findObjectMutex.RLock()
	defer fake.findObjectMutex.RUnlock()
	fake.findUserMutex.RLock()
	defer fake.findUserMutex.RUnlock()
	fake.getCollectionMutex.RLock()
	defer fake.getCollectionMutex.RUnlock()
	fake.getDatabaseMutex.RLock()
	defer fake.getDatabaseMutex.RUnlock()
	fake.insertDataMutex.RLock()
	defer fake.insertDataMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeMongoClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ util.MongoClient = new(FakeMongoClient)
